/**
 * Description des champs de chaque document, pour guider l'extraction IA.
 * Les clés correspondent exactement aux champs des formulaires.
 */
export type Champ = { key: string; desc: string };

const COMMUN_EMPLOYEUR: Champ[] = [
  { key: "entrepriseNom", desc: "Nom de l'entreprise / employeur" },
  { key: "entrepriseAdresse", desc: "Adresse de l'entreprise" },
  { key: "siret", desc: "Numéro SIRET" },
];

const REPRESENTANT: Champ[] = [
  { key: "representantNom", desc: "Nom du représentant légal" },
  {
    key: "representantQualite",
    desc: "Qualité du représentant (Gérant, Président…)",
  },
];

export const CHAMPS: Record<string, Champ[]> = {
  "quittance-loyer": [
    { key: "bailleurNom", desc: "Nom du bailleur (propriétaire)" },
    { key: "bailleurAdresse", desc: "Adresse du bailleur" },
    { key: "locataire", desc: "Nom du locataire" },
    { key: "adresseBien", desc: "Adresse du logement loué" },
    { key: "periode", desc: "Période concernée (ex. Juin 2026)" },
    { key: "loyer", desc: "Montant du loyer hors charges, en euros (nombre)" },
    { key: "charges", desc: "Montant des charges, en euros (nombre)" },
    { key: "ville", desc: "Ville de signature" },
    { key: "datePaiement", desc: "Date de paiement (JJ/MM/AAAA)" },
  ],
  "attestation-employeur": [
    ...COMMUN_EMPLOYEUR,
    ...REPRESENTANT,
    { key: "salarieNom", desc: "Nom et prénom du salarié" },
    { key: "poste", desc: "Poste occupé" },
    {
      key: "typeContrat",
      desc: "Type de contrat : « indeterminee » (CDI) ou « determinee » (CDD)",
    },
    { key: "dateEmbauche", desc: "Date d'embauche (JJ/MM/AAAA)" },
    { key: "ville", desc: "Ville de signature" },
    { key: "date", desc: "Date du document (JJ/MM/AAAA)" },
  ],
  "fiche-paie": [
    ...COMMUN_EMPLOYEUR,
    { key: "salarieNom", desc: "Nom et prénom du salarié" },
    { key: "poste", desc: "Poste" },
    { key: "numeroSecu", desc: "Numéro de sécurité sociale" },
    { key: "periode", desc: "Période de paie (ex. Juin 2026)" },
    { key: "salaireBrut", desc: "Salaire brut mensuel, en euros (nombre)" },
    { key: "heuresSup", desc: "Heures supplémentaires (nombre)" },
    { key: "primes", desc: "Montant des primes, en euros (nombre)" },
  ],
  "contrat-travail": [
    ...COMMUN_EMPLOYEUR,
    ...REPRESENTANT,
    { key: "salarieNom", desc: "Nom et prénom du salarié" },
    { key: "salarieAdresse", desc: "Adresse du salarié" },
    { key: "typeContrat", desc: "Type : « cdi » ou « cdd »" },
    { key: "dateDebut", desc: "Date de début (JJ/MM/AAAA)" },
    { key: "dateFin", desc: "Date de fin si CDD (JJ/MM/AAAA)" },
    { key: "motifCdd", desc: "Motif du CDD le cas échéant" },
    { key: "poste", desc: "Poste / intitulé du poste" },
    { key: "salaireBrut", desc: "Salaire brut mensuel, en euros (nombre)" },
    { key: "heuresSemaine", desc: "Heures par semaine (nombre, défaut 35)" },
    { key: "lieuTravail", desc: "Lieu de travail" },
    { key: "periodeEssai", desc: "Période d'essai (ex. 2 mois)" },
    { key: "conventionCollective", desc: "Convention collective applicable" },
    { key: "ville", desc: "Ville de signature" },
    { key: "date", desc: "Date de signature (JJ/MM/AAAA)" },
  ],
  "certificat-travail": [
    ...COMMUN_EMPLOYEUR,
    ...REPRESENTANT,
    { key: "salarieNom", desc: "Nom et prénom du salarié" },
    { key: "poste", desc: "Poste occupé" },
    { key: "dateDebut", desc: "Date d'entrée (JJ/MM/AAAA)" },
    { key: "dateFin", desc: "Date de sortie (JJ/MM/AAAA)" },
    { key: "ville", desc: "Ville de signature" },
    { key: "date", desc: "Date de délivrance (JJ/MM/AAAA)" },
  ],
  "solde-tout-compte": [
    ...COMMUN_EMPLOYEUR,
    ...REPRESENTANT,
    { key: "salarieNom", desc: "Nom et prénom du salarié" },
    { key: "salarieAdresse", desc: "Adresse du salarié" },
    { key: "poste", desc: "Poste occupé" },
    { key: "dateEntree", desc: "Date d'entrée (JJ/MM/AAAA)" },
    { key: "dateSortie", desc: "Date de sortie (JJ/MM/AAAA)" },
    { key: "motifRupture", desc: "Motif de la rupture" },
    { key: "salaireDu", desc: "Salaire et accessoires dus, en euros (nombre)" },
    { key: "indemniteConges", desc: "Indemnité de congés payés (nombre)" },
    { key: "indemnitePreavis", desc: "Indemnité de préavis (nombre)" },
    { key: "indemniteRupture", desc: "Indemnité de rupture (nombre)" },
    { key: "autresSommes", desc: "Autres sommes (nombre)" },
    { key: "ville", desc: "Ville de signature" },
    { key: "date", desc: "Date de signature (JJ/MM/AAAA)" },
  ],
  "rupture-conventionnelle": [
    ...COMMUN_EMPLOYEUR,
    ...REPRESENTANT,
    { key: "salarieNom", desc: "Nom et prénom du salarié" },
    { key: "salarieAdresse", desc: "Adresse du salarié" },
    { key: "poste", desc: "Poste occupé" },
    { key: "dateEmbauche", desc: "Date d'embauche (JJ/MM/AAAA)" },
    { key: "salaireBrut", desc: "Salaire brut mensuel, en euros (nombre)" },
    { key: "indemniteRupture", desc: "Indemnité de rupture, en euros (nombre)" },
    { key: "dateEntretien", desc: "Date de l'entretien (JJ/MM/AAAA)" },
    { key: "dateRupture", desc: "Date envisagée de rupture (JJ/MM/AAAA)" },
    { key: "ville", desc: "Ville de signature" },
    { key: "date", desc: "Date de signature (JJ/MM/AAAA)" },
  ],
  "bail-commercial": [
    { key: "bailleurNom", desc: "Nom / dénomination du bailleur" },
    { key: "bailleurAdresse", desc: "Adresse du bailleur" },
    { key: "bailleurQualite", desc: "Qualité du bailleur (SCI, particulier…)" },
    { key: "preneurNom", desc: "Nom / dénomination du preneur (locataire)" },
    { key: "preneurAdresse", desc: "Adresse du preneur" },
    { key: "preneurRcs", desc: "Numéro RCS du preneur" },
    { key: "adresseLocal", desc: "Adresse du local commercial loué" },
    { key: "descriptionLocal", desc: "Description du local" },
    { key: "surface", desc: "Surface en m² (nombre)" },
    { key: "destination", desc: "Activité / destination autorisée" },
    { key: "loyerAnnuel", desc: "Loyer annuel HT/HC, en euros (nombre)" },
    { key: "depotGarantie", desc: "Dépôt de garantie, en euros (nombre)" },
    { key: "charges", desc: "Modalités des charges" },
    { key: "indiceRevision", desc: "Indice de révision (ILC, ILAT…)" },
    { key: "dateDebut", desc: "Date de prise d'effet (JJ/MM/AAAA)" },
    { key: "duree", desc: "Durée du bail (ex. 9 ans)" },
    { key: "ville", desc: "Ville de signature" },
    { key: "date", desc: "Date de signature (JJ/MM/AAAA)" },
  ],
  "statuts-societe": [
    {
      key: "forme",
      desc: "Forme juridique : SARL, SAS, EURL ou SASU (en majuscules)",
    },
    { key: "denomination", desc: "Dénomination sociale" },
    { key: "objet", desc: "Objet social (activité)" },
    { key: "siege", desc: "Adresse du siège social" },
    { key: "duree", desc: "Durée de la société (ex. 99 ans)" },
    { key: "valeurTitre", desc: "Valeur nominale d'une part/action (nombre)" },
    { key: "dirigeantNom", desc: "Nom du gérant / président" },
    { key: "dirigeantAdresse", desc: "Adresse du dirigeant" },
    { key: "ville", desc: "Ville de signature" },
    { key: "date", desc: "Date de signature (JJ/MM/AAAA)" },
  ],
};
